dist: bionic

language: scala

scala:
  - "2.12.12"

jdk: oraclejdk11

cache:
  directories:
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt        -name "*.lock"               -delete

install:
  - git fetch --tags

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean headerCheck scalastyle test:scalastyle coverage test coverageReport scripted

before_deploy:
  - if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      openssl aes-256-cbc -K $encrypted_82c15cb04022_key -iv $encrypted_82c15cb04022_iv -in secring.asc.enc -out secring.asc -d;
      gpg --batch --import secring.asc;
      rm secring.asc;
    fi

deploy:
  - provider: script
    skip_cleanup: true
    script: sbt ++$TRAVIS_SCALA_VERSION coverageOff publishSigned
    on:
      tags: false
      all_branches: true
  - provider: script
    skip_cleanup: true
    script: sbt ++$TRAVIS_SCALA_VERSION coverageOff publishSigned sonatypeBundleRelease
    on:
      tags: true

env:
  global:
    - secure: "lg0z7sTC/i0+IjePIwd1dsgZi+RiN1kxahNVlUs/6T/IIJwvWOs3Uf6CXuughaebkbcC3iIk/kLAeU+WbKV0c/syf7vxzzzMtgjTge3m3k94Hjyo+JxvRyfpZ0d6GWVpyBfLdnOlq2myPeM79naxw7nPFlP1/s/rYmuARzWsjzKckDcjxRABTf5YEsqTunGSXBnBCjmejN0Rh8qL7e5XUKfRDL6wb3B/V3/gd6fZacv58jqRq2XyiAyO0YQxIbsBCS1g+EZudeakynkco5ci3JsdrqwC7pups/pm0T3/ftst5ZXOjKBHx7I1zMtsATL71ZD0bzI7PKLooRytIK4bAVtXQmC65wKSSe9Q4DrXPixOqFcu9ZYjU8ZjfaBfuPZfTK1Da9TBkTYNq1s+KTu07I7SK3lsSpRRrC4OT4jH1q9d6PnNf71iymHGgr5rcqgKJFD5TLEP1VpYgD6iNItIaIwgZ9smm7lfRG6lpe8hK92v0U/iPNFE4AKblmcCw8QekqZrvxyTPS4B7BmammGD9UCwhb1gMxfEPIP8/cWOyPPgKKT3EPzLyzDsePPnAjLgb4bHWf2jBMaVV3sbhPtY9Gzw/Q8UJScC/sGiaQ0cXeTS3FODe2D2ZOYFNal62c+/7tfqE7KxulMZ7QPYVBySrXEo9dAIJt65hiSWuDbmBJs="
    - secure: "hW3Q4S/kXrkBV1+DcqftP+fJQiVOfhiKmkpkPjwn8ADZibJCO/TTt1ovxPCXW4CmGNDeY2GXAUz3FQflWqIeHXclu9i46k18qjMggd7+lYXogMMHoD+YPzRRKxJ28W7i6nyxSQ4VyvaFx3qXxIOO/htuCN0dmT6rdRpfaXXCTctcFOtvrKsbcrnVmsFOgP/CyCpzoqCbviyVZ6DtZbwuSrwxn4gFcRUfgWs0eU5CSrcd1Simcsia3DAnKfQ9uTnPDhYWCc+8DYVrRyWd6tZzwoRb7BlpTx17/ppPgF6tHtznu9o2h2AO4JVtt4UKMQ62XqMyW8vfNaANLkDxLtigiAO7zMdhMi9RkRXzTV6phBGt4SJ3m19E3oesqW/Vd0vSx0XN9ZpE62W1QrDLgGIJwKgyLO9a3nX6nPiGlr0taHRrVENLODIGZ6DI9+saXPBg4O3ESld0V9+/XapNFSGtvepiQ3oT8KOyjxsg6fldXjy1OgXUPfsXQrckEbv9eAXpVAPqtR96ULzCy3kkTbjFx2gpFaqc3R5xDArRf/OnOeV1TiXByMNlbw78pX0XNb5aLTxVFqQlNxmA/lK+MWnTQYujTsY1LSkCvmdEBlZub1OkBWGQEX8w/F6KOtok1SqlOW0sdANN4JP5A7WS4fcpTXh1Fe+HyKDwORkqHycvpU0="
    - secure: "rsav5lbZB6Q4p4UcQ32FQgNBIfC4c1HM1q/u4a8Zuvw2mn7GoOAb8day76OfRamXHM5qfhoFc0wunytssRQfuK1qpQZDqCp1PP89FQY66p4F86N4jKkUb6kT2/dfuE2OJYYqllYHYr3qjN4calY+ARgtQkRTkgqqwKTZ+C/zhqhRxvTNxNc0yCdOB/1CR/pz0Hy2CeX+P6tNlAjYOtCBW4iuyRheu6nU+ciSZsXXBDyR85P9lIWqOF78CB6zo02b4kOXyVlCHMtdJkEuZvdHgIytxkTnKqdTcosz7F+F9rjvkz+Is13taT3YNpDwP8oCtKtPRAypi7MUyOn1DuJ3FEEKwgpIn+4ow1qoCBckJqhTKgXBmYHmtnDLi36IOssCo6diHQmIWG23u+VT0L1MWUtumdyBvKW5nQp/IDdP0a34FHwYW/rHiNVh/Eoiwsn5/wajhQGSlD0Sx3SkW3pfLXycI86tuznKlLblYXVgfWBChQQYObRcog9H4JafXqAe/02HMndapSedgGlj2fUEvhPntyNYRi0upqxEZfZCH3xE3M9t67SXA9yn0DnCDeSmHoN3vs7BHfPZI6gtHtIzbiPKCEMcRi9E6puFn75QcN0apY+EtvhphBvpA67rviHLP7T009kK27PGkcavo5CDzgY2eUMQ1+9bCLN2SIvOhP4="
